### ISSUE TITLE
Add template tag for "add new item"

### ISSUE THREAD

**Issue by bittner** [mikebader/django-vitae#1]
The project has quite a few [section types](https://github.com/mikebader/django-vitae/tree/master/cv/templates/cv/sections), which all seem to have a "Add new *section*" link at the end of a section to allow adding new items. The related code is duplicated all over the templates (e.g. [degrees](https://github.com/mikebader/django-vitae/blob/master/cv/templates/cv/sections/degrees.html#L23-L29), [books](https://github.com/mikebader/django-vitae/blob/master/cv/templates/cv/sections/books.html#L52-L58), [articles](https://github.com/mikebader/django-vitae/blob/master/cv/templates/cv/sections/articles.html#L59-L65), [grants](https://github.com/mikebader/django-vitae/blob/master/cv/templates/cv/sections/grants.html#L37-L43), [students](https://github.com/mikebader/django-vitae/blob/master/cv/templates/cv/sections/students.html#L16-L22), [talks](https://github.com/mikebader/django-vitae/blob/master/cv/templates/cv/sections/talks.html#L17-L23)).

Instead of duplicating code, a template tag shall implement the internals and the templates shall call the template tag with appropriate parameters. Similar for [editing existing items](https://github.com/mikebader/django-vitae/blob/master/cv/templates/cv/sections/positions.html#L20-L22).

**Comment by mikebader** [comment]
Thank you for catching this. There is a template tag `add_publication <model_name>`. I applied it to all of the models on the `dev` branch. The name is not great, so I think that I will change the template tag to `add_item <model_name>` when I create the template tag for editing items.

**Comment by bittner** [comment]
Awesome! :astonished: :smiley: 

With [those changes](https://github.com/mikebader/django-vitae/commit/322235d0ffe662d263627188fcccb6c70a9a58c4) the code looks much nicer.

Maybe you want to add a similar change to the edit links? Not all sections seem to allow editing, though. I'm not sure why.

**Comment by mikebader** [comment]
Thanks! 

I just changed the template tag to `item_add` and created a corresponding `item_edit` template tag as well. I'll write a separate ticket for the missing classes without an edit link (I think it's just for talks, and it's because I need to create the formsets for individual presentations of the talk).
